In [17]:
import pandas as pd 
# import matplotlib as plt

df = pd.read_csv("paniers.csv")
df.head(2)

,id_panier,label_panier,type_panier,id_utilisateur,actif,nombre_produits,date_publication,utilisateur_creation,date_creation,utilisateur_modification,date_modification,image,presentation,links
0,d19b22f0-9cb9-4c08-91e0-9fcae93adee1,MAM,PERSO,9f44a944-1b37-4bdb-b8b6-c478d2bca598,True,5,2025-05-13,mdydy155@gmail.com,2025-05-13,NaN,NaN,NaN,NaN,{'self': {'href': 'https://prix.nc/api/v1/pani...
1,5035a78d-a851-43ee-b32e-5e56741decba,Entretien/hygienne,PERSO,fdcf4a8d-742b-4710-a704-7fb842e12385,True,10,2025-04-27,rdawano@gmail.com,2025-04-01,rdawano@gmail.com,2025-04-27,NaN,NaN,{'self': {'href': 'https://prix.nc/api/v1/pani...

In [58]:
df.isnull().sum()

id_panier                   0
label_panier                0
type_panier                 0
id_utilisateur              0
actif                       0
nombre_produits             0
date_publication            0
utilisateur_creation        0
date_creation               0
utilisateur_modification    0
date_modification           0
image                       0
presentation                0
links                       0
dtype: int64

In [ ]:
data = df 
data[["image"]] = data[["image"]].fillna("vide")
data[["image"]]
data.head(4)

:

In [36]:
data[["presentation"]] = data[["presentation"]].fillna("Acunne")
data[["presentation"]].head(2)

  presentation
0       Acunne
1       Acunne

In [48]:
data[["date_modification"]].to_timestamp
dt = data
db = data
dt[["date_modification"]] = dt[["date_modification"]].fillna(pd.to_datetime("1999-01-01"))
dt["date_modification"] = pd.to_datetime(dt['date_modification']).dt.date
dt[["date_modification"]]

    date_modification
0          1999-01-01
1          2025-04-27
2          1999-01-01
3          1999-01-01
4          1999-01-01
..                ...
275        2018-01-09
276        2018-01-09
277        2018-01-09
278        2018-01-09
279        2018-04-03

[280 rows x 1 columns]

In [57]:
db["utilisateur_modification"] = db["utilisateur_modification"].fillna("vide")
db["utilisateur_modification"]

0                   vide
1      rdawano@gmail.com
2                   vide
3                   vide
4                   vide
             ...
275       Mathilde MENIL
276       Mathilde MENIL
277       Mathilde MENIL
278       Mathilde MENIL
279       Mathilde MENIL
Name: utilisateur_modification, Length: 280, dtype: str

In [ ]:
db.head(12)

: