In [3]:
import pandas as pd 


data =  pd.read_excel("Classeur_TCD.xlsx")

data.head(1)

,Date de Saisie,N° ORDRE,AGENCE RÉGIONALE,NOM DU BENEFICIAIRE,PRENOM (S) DU BENEFICIAIRE,SEXE,DATE NAISSANCE,LIEU DE NAISSANCE,SOUS PREFECTURE OU COMMUNE DE NAISSANCE,HANDICAP,...,BRANCHE D’ACTIVITE DE L’ENTREPRISE,SERVICE D'AFFECTATION,l,DUREE PREVISIONNELLE,DATE DE FIN PREVISIONNELLE,LOCALITE DE RESIDENCE HABITUELLE,LOCALITE DU LIEU DE STAGE,AUTRE TYPE DE PAIEMENT,TYPE D'ENTREPRISE,Unnamed: 39
0,2026-06-17 00:00:00,31,BOUAKE,KOUAKOU,AYA SARAH,FEMME,30/06/2006,BOUAKE,BOUAKE,SANS HANDICAP,...,Reception,RECEPTION,KOUAKOU AYA SARAH né le 30/06/2006 à BOUAKE,1,31/07/2026,BOUAKE,BOUAKE,MME DOUMBIA,SOUS DIRECTRICE DES MOYENS GENERAUX DES RESSOU...,709081952.0

In [10]:
df = data.copy

# df.culumns()

In [14]:
data.columns

Index(['Date de Saisie', 'N° ORDRE', 'AGENCE RÉGIONALE', 'NOM DU BENEFICIAIRE',
       'PRENOM (S) DU BENEFICIAIRE', 'SEXE', 'DATE NAISSANCE',
       'LIEU DE NAISSANCE', 'SOUS PREFECTURE OU COMMUNE DE NAISSANCE',
       'HANDICAP', 'AUTRE TYPE DE HANDICAP', 'NATURE PIECE D'IDENTITE',
       'NUMERO PIECE IDENTITE', 'CONTACT 1', 'CONTACT 2', 'NIVEAU D'ETUDE',
       'ETABLISSEMENT FREQUENTE', 'TYPE D'ENSEIGNEMENT',
       'SOUS PREFECTURE DE RESIDENCE', 'TYPE DE PAIEMENT', 'N° DE PAIEMENT',
       'NOM ET PRENOM(S) DU TUTEUR', 'LIEN DE PARENTE DU TUTEUR',
       'CONTACT DU TUTEUR', 'DATE DE DEBUT DU STAGE',
       'SOUS PREFECTURE DU LIEU STAGE',
       'DEPARTEMENT ADMINISTRATIF DU LIEU DE STAGE', 'ENTREPRISE',
       'CONTACT ENTREPRISE 1', 'CONTACT ENTREPRISE 2',
       'BRANCHE D’ACTIVITE DE L’ENTREPRISE', 'SERVICE D'AFFECTATION', 'l',
       'DUREE PREVISIONNELLE', 'DATE DE FIN PREVISIONNELLE',
       'LOCALITE DE RESIDENCE HABITUELLE', 'LOCALITE DU LIEU DE STAGE',
       'AUTRE TYPE DE PAIEMENT', 'TYPE D'ENTREPRISE', 'Unnamed: 39'],
      dtype='str')

In [58]:
data.isnull().sum()

Date de Saisie                                 0
N° ORDRE                                       0
AGENCE RÉGIONALE                               0
NOM DU BENEFICIAIRE                            0
PRENOM (S) DU BENEFICIAIRE                     0
SEXE                                           0
DATE NAISSANCE                                 0
LIEU DE NAISSANCE                              0
SOUS PREFECTURE OU COMMUNE DE NAISSANCE        0
HANDICAP                                       0
AUTRE TYPE DE HANDICAP                         0
NATURE PIECE D'IDENTITE                        0
NUMERO PIECE IDENTITE                          0
CONTACT 1                                      0
CONTACT 2                                      0
NIVEAU D'ETUDE                                 0
ETABLISSEMENT FREQUENTE                        0
TYPE D'ENSEIGNEMENT                            0
SOUS PREFECTURE DE RESIDENCE                   0
TYPE DE PAIEMENT                               0
N° DE PAIEMENT                                 0
NOM ET PRENOM(S) DU TUTEUR                     0
LIEN DE PARENTE DU TUTEUR                      0
CONTACT DU TUTEUR                              0
DATE DE DEBUT DU STAGE                         0
SOUS PREFECTURE DU LIEU STAGE                  0
DEPARTEMENT ADMINISTRATIF DU LIEU DE STAGE     0
ENTREPRISE                                     0
CONTACT ENTREPRISE 1                           0
CONTACT ENTREPRISE 2                          64
BRANCHE D’ACTIVITE DE L’ENTREPRISE             0
SERVICE D'AFFECTATION                          0
l                                              0
DUREE PREVISIONNELLE                           0
DATE DE FIN PREVISIONNELLE                     0
LOCALITE DE RESIDENCE HABITUELLE               0
LOCALITE DU LIEU DE STAGE                      0
AUTRE TYPE DE PAIEMENT                        41
TYPE D'ENTREPRISE                              4
Unnamed: 39                                   42
dtype: int64

In [ ]:
data[["AUTRE TYPE DE HANDICAP"]] = data[["AUTRE TYPE DE HANDICAP"]].fillna("SANS HANDICAP")

In [29]:
data[["CONTACT 2"]] = data[["CONTACT 2"]].fillna(0)

In [80]:
emt = data.groupby("ENTREPRISE").agg(
    total_persones = ("NOM DU BENEFICIAIRE", "count")
)
emt = emt.sort_values("total_persones", ascending= False)
emt.head(17)

                                                    total_persones
ENTREPRISE
MAIRIE DE BOUAKE                                                47
ETABLISSEMENT PUBLIC HOSPITALIER REGIONAL DE BO...              18
CLINIQUE MEDICALE TOURE                                          6
PRO SOFT                                                         5
DIVINE TOPOBAT SERVICES                                          4
NOUR DISTRIBUTION                                                4
ETS KOFFI YAO ANGE                                               3
CENTRE CULTUREL JACQUES AKA BOUAKE                               2
DIRECTION REGIONAL DU MINISTERE  DU PETROLE ET ...               2
GROUPE GREABOUL                                                  2
GROUPE BMS SARL                                                  2
MAIRIE DE BOTRO                                                  2
PREFECTURE DE BOTRO                                              2
PHARMACIE ESPOIR                                                 2
DIRECTION REGIONALE DE LA PROTECTION SOCIALE                     2
DIRECTION REGIONALE DE LA COHESION NATIONALE ET...               2
DIRECTION DU CENTRE SOCIAL BOTRO                                 1

In [71]:
etb = data.groupby("ETABLISSEMENT FREQUENTE").agg(
    total_persones = ("NOM DU BENEFICIAIRE", "count")
    ).reset_index()
etb = etb.sort_values("total_persones", ascending= False)
etb.head(5)

etb.to_excel("etablissement.xlsx")

In [73]:
sexe = data.groupby("SEXE").agg(
    totale_persones = ("NOM DU BENEFICIAIRE", "count")
)
sexe = sexe.sort_values("totale_persones", ascending= False)

sexe.head(4)
sexe.to_excel("sexe.xlsx")

,total_persones,ETABLISSEMENT FREQUENTE
MAIRIE DE BOUAKE,47,NaN
ETABLISSEMENT PUBLIC HOSPITALIER REGIONAL DE BOUAKE,18,NaN
CLINIQUE MEDICALE TOURE,6,NaN
PRO SOFT,5,NaN
DIVINE TOPOBAT SERVICES,4,NaN
...,...,...
82,1,UNIVERSITE ALASSANE OUATTARA\t
83,1,UNIVERSITE ALASSANE OUATTARA BOUAKE
84,1,UNIVERSITE ALASSANE OUATTARA BOUAKE
85,1,UNIVERSITE DE L'ATLANTIQUE
86,1,UNIVERSITE NORD SUD BOUAKE